version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: carsInventory_container
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    container_name: carsInventory
    image: carsinventory
    ports:
      - 3050:3050
    depends_on: 
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/

volumes:
  mongo_data: {}